enableTelemetry: false

packageExtensions:
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"
  "@inquirer/checkbox@4.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/confirm@5.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/core@10.0.0":
    dependencies:
      "@types/node": "*"
  "@inquirer/editor@4.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/expand@4.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/input@4.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/number@3.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/password@4.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/rawlist@4.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/search@3.0.0":
    dependencies:
       "@types/node": "*"
  "@inquirer/select@4.0.0":
    dependencies:
       "@types/node": "*"

pnpMode: strict